# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6abf339cd19cfcf65c39a3c362cfa7ae1501d42276434de6e9300caa1f9d08653687fd4d10bc310aa3965d50972dfd398d3ecfee0ca803bf8353073132f36259

test:
  secret_key_base: 88c853a4da71ce7e5711f27cef7e09d1e2e9e67c4a5a005b3eafebcd4449eb1da784374c49e28e321cce2bf24806d5de1beb96a14259da5dedf0fd31b71b87bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
